{"uid":"90ff074e97d5d09e","name":"test_clean_issue[eroshenkoam/allure-example-\\u0422\\u0435\\u0441\\u0442\\u0438\\u0440\\u0443\\u0435\\u043c \\u0442\\u0435\\u0441\\u0442]","fullName":"tests.test_marked_tests#test_clean_issue","historyId":"7c66044b19295911e1257008f62ff293","time":{"start":1738099805557,"stop":1738099805557,"duration":0},"description":"\nПроверка наличия конкретного Issue в репозитории на GitHub.\n:param repo_name: Имя репозитория (например, 'eroshenkoam/allure-example')\n:param issue_text: Текст искомого Issue (например, 'Тестируем тест')\n","descriptionHtml":"<p>Проверка наличия конкретного Issue в репозитории на GitHub.<br />\n:param repo_name: Имя репозитория (например, 'eroshenkoam/allure-example')<br />\n:param issue_text: Текст искомого Issue (например, 'Тестируем тест')</p>\n","status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nStacktrace:\n#0 0x563ad3d8cdca <unknown>\n#1 0x563ad38833f0 <unknown>\n#2 0x563ad38ba47a <unknown>\n#3 0x563ad38b69b6 <unknown>\n#4 0x563ad3903ca6 <unknown>\n#5 0x563ad39032f6 <unknown>\n#6 0x563ad38f7833 <unknown>\n#7 0x563ad38c45a0 <unknown>\n#8 0x563ad38c5ece <unknown>\n#9 0x563ad3d56bdb <unknown>\n#10 0x563ad3d5ab67 <unknown>\n#11 0x563ad3d423bc <unknown>\n#12 0x563ad3d5b727 <unknown>\n#13 0x563ad3d2674f <unknown>\n#14 0x563ad3d7b938 <unknown>\n#15 0x563ad3d7bb00 <unknown>\n#16 0x563ad3d8bc46 <unknown>\n#17 0x7fc5cba9ca94 <unknown>\n#18 0x7fc5cbb29c3c <unknown>","statusTrace":"@pytest.fixture(scope=\"session\", autouse=True)\n    @allure.step(\"Настройка браузера\")\n    def browser_set():\n        driver_options = webdriver.ChromeOptions()\n        driver_options.page_load_strategy = \"eager\"\n        browser.config.driver_options = driver_options\n        browser.config.base_url = \"https://github.com\"\n>       browser.driver.set_window_size(1920, 1080)\n\ntests/conftest.py:14: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/selene/core/_browser.py:34: in driver\n    return self.config.driver\n/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/selene/core/configuration.py:305: in __get__\n    driver = config.build_driver_strategy(config)\n/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/selene/core/configuration.py:129: in _build_local_driver_by_name_or_remote_by_url_and_options\n    return {  # type: ignore\n/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/selene/core/configuration.py:66: in build_chrome\n    return Chrome(\n/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/selenium/webdriver/chrome/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/selenium/webdriver/chromium/webdriver.py:66: in __init__\n    super().__init__(command_executor=executor, options=options)\n/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:250: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:342: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py:429: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f9e9e77dcd0>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"session not created\",\"message\":\"session not created: probably user data d...\\\\n#16 0x563ad3d8bc46 \\\\u003Cunknown>\\\\n#17 0x7fc5cba9ca94 \\\\u003Cunknown>\\\\n#18 0x7fc5cbb29c3c \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nE       Stacktrace:\nE       #0 0x563ad3d8cdca <unknown>\nE       #1 0x563ad38833f0 <unknown>\nE       #2 0x563ad38ba47a <unknown>\nE       #3 0x563ad38b69b6 <unknown>\nE       #4 0x563ad3903ca6 <unknown>\nE       #5 0x563ad39032f6 <unknown>\nE       #6 0x563ad38f7833 <unknown>\nE       #7 0x563ad38c45a0 <unknown>\nE       #8 0x563ad38c5ece <unknown>\nE       #9 0x563ad3d56bdb <unknown>\nE       #10 0x563ad3d5ab67 <unknown>\nE       #11 0x563ad3d423bc <unknown>\nE       #12 0x563ad3d5b727 <unknown>\nE       #13 0x563ad3d2674f <unknown>\nE       #14 0x563ad3d7b938 <unknown>\nE       #15 0x563ad3d7bb00 <unknown>\nE       #16 0x563ad3d8bc46 <unknown>\nE       #17 0x7fc5cba9ca94 <unknown>\nE       #18 0x7fc5cbb29c3c <unknown>\n\n/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py:232: SessionNotCreatedException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"browser_set","time":{"start":1738099805279,"stop":1738099805459,"duration":180},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nStacktrace:\n#0 0x563ad3d8cdca <unknown>\n#1 0x563ad38833f0 <unknown>\n#2 0x563ad38ba47a <unknown>\n#3 0x563ad38b69b6 <unknown>\n#4 0x563ad3903ca6 <unknown>\n#5 0x563ad39032f6 <unknown>\n#6 0x563ad38f7833 <unknown>\n#7 0x563ad38c45a0 <unknown>\n#8 0x563ad38c5ece <unknown>\n#9 0x563ad3d56bdb <unknown>\n#10 0x563ad3d5ab67 <unknown>\n#11 0x563ad3d423bc <unknown>\n#12 0x563ad3d5b727 <unknown>\n#13 0x563ad3d2674f <unknown>\n#14 0x563ad3d7b938 <unknown>\n#15 0x563ad3d7bb00 <unknown>\n#16 0x563ad3d8bc46 <unknown>\n#17 0x7fc5cba9ca94 <unknown>\n#18 0x7fc5cbb29c3c <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/_pytest/fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/qa_lesson_10/qa_lesson_10/tests/conftest.py\", line 14, in browser_set\n    browser.driver.set_window_size(1920, 1080)\n    ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/selene/core/_browser.py\", line 34, in driver\n    return self.config.driver\n           ^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/selene/core/configuration.py\", line 305, in __get__\n    driver = config.build_driver_strategy(config)\n  File \"/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/selene/core/configuration.py\", line 129, in _build_local_driver_by_name_or_remote_by_url_and_options\n    return {  # type: ignore\n           ~~~~~~~~~~~~~~~~~\n    ...<32 lines>...\n        )\n        ~\n    )()\n    ~^^\n  File \"/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/selene/core/configuration.py\", line 66, in build_chrome\n    return Chrome(\n        service=config.driver_service or ChromeService(),\n        options=config.driver_options,\n    )\n  File \"/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n    ~~~~~~~~~~~~~~~~^\n        browser_name=DesiredCapabilities.CHROME[\"browserName\"],\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<3 lines>...\n        keep_alive=keep_alive,\n        ^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/selenium/webdriver/chromium/webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 250, in __init__\n    self.start_session(capabilities)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 342, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[{"name":"Настройка браузера","time":{"start":1738099805279,"stop":1738099805457,"duration":178},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nStacktrace:\n#0 0x563ad3d8cdca <unknown>\n#1 0x563ad38833f0 <unknown>\n#2 0x563ad38ba47a <unknown>\n#3 0x563ad38b69b6 <unknown>\n#4 0x563ad3903ca6 <unknown>\n#5 0x563ad39032f6 <unknown>\n#6 0x563ad38f7833 <unknown>\n#7 0x563ad38c45a0 <unknown>\n#8 0x563ad38c5ece <unknown>\n#9 0x563ad3d56bdb <unknown>\n#10 0x563ad3d5ab67 <unknown>\n#11 0x563ad3d423bc <unknown>\n#12 0x563ad3d5b727 <unknown>\n#13 0x563ad3d2674f <unknown>\n#14 0x563ad3d7b938 <unknown>\n#15 0x563ad3d7bb00 <unknown>\n#16 0x563ad3d8bc46 <unknown>\n#17 0x7fc5cba9ca94 <unknown>\n#18 0x7fc5cbb29c3c <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/home/runner/work/qa_lesson_10/qa_lesson_10/tests/conftest.py\", line 14, in browser_set\n    browser.driver.set_window_size(1920, 1080)\n    ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/selene/core/_browser.py\", line 34, in driver\n    return self.config.driver\n           ^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/selene/core/configuration.py\", line 305, in __get__\n    driver = config.build_driver_strategy(config)\n  File \"/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/selene/core/configuration.py\", line 129, in _build_local_driver_by_name_or_remote_by_url_and_options\n    return {  # type: ignore\n           ~~~~~~~~~~~~~~~~~\n    ...<32 lines>...\n        )\n        ~\n    )()\n    ~^^\n  File \"/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/selene/core/configuration.py\", line 66, in build_chrome\n    return Chrome(\n        service=config.driver_service or ChromeService(),\n        options=config.driver_options,\n    )\n  File \"/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n    ~~~~~~~~~~~~~~~~^\n        browser_name=DesiredCapabilities.CHROME[\"browserName\"],\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<3 lines>...\n        keep_alive=keep_alive,\n        ^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/selenium/webdriver/chromium/webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 250, in __init__\n    self.start_session(capabilities)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 342, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":1,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"afterStages":[],"labels":[{"name":"severity","value":"critical"},{"name":"story","value":"Issue Verification in Repository"},{"name":"feature","value":"GitHub Repository Testing"},{"name":"tag","value":"Allure"},{"name":"tag","value":"GitHub"},{"name":"tag","value":"Selene"},{"name":"epic","value":"UI Tests"},{"name":"tag","value":"ui"},{"name":"tag","value":"critical"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_marked_tests"},{"name":"host","value":"fv-az1441-609"},{"name":"thread","value":"3109-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_marked_tests"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"issue_text","value":"'Тестируем тест'"},{"name":"repo_name","value":"'eroshenkoam/allure-example'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"critical","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":["ui","critical","GitHub","Selene","Allure"]},"source":"90ff074e97d5d09e.json","parameterValues":["'Тестируем тест'","'eroshenkoam/allure-example'"]}